version: '3.4'

####################################################################
# The block are defined the basic services. 
# If you want to add some configuration options, 
# You should add configuration options to 'docker-compose.override.yml'
####################################################################
services:

  rabbitmq:
    image: "rabbitmq:3-management-alpine"

  redis:
    image: "redis:alpine"

  zipkin:
    image: "openzipkin/zipkin:latest"

  dapr-placement:
    image: "daprio/dapr:1.0.0"

  ####################################################################
  # Web Api Service and dapr services
  ####################################################################
  dapr_aspnetcore:
    image: ${DOCKER_REGISTRY-}dapraspnetcore
    build:
      context: .
      dockerfile: dapr_aspnetcore/Dockerfile
   
  dapr_aspnetcore-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      "-app-id", "dapr_aspnetcore", 
      "-app-port", "80" 
      ]

  News_WebApi:
    image: ${DOCKER_REGISTRY-}newswebapi
    build:
      context: .
      dockerfile: ApiServices/News.Web.Api/News.Web.Api/Dockerfile
   
  News_WebApi-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      "-app-id", "News_WebApi", 
      "-app-port", "80" 
      ]

  Article_WebApi:
    image: ${DOCKER_REGISTRY-}articlewebapi
    build:
      context: .
      dockerfile: ApiServices/Article.Web.Api/Article.Web.Api/Dockerfile
   
  Article_WebApi-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      "-app-id", "Article_WebApi", 
      "-app-port", "80" 
      ]

  MainWebApi:
    image: ${DOCKER_REGISTRY-}mainwebapi
    build:
      context: .
      dockerfile: MainWebApi/Dockerfile
   
  MainWebApi-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      "-app-id", "MainWebApi", 
      "-app-port", "80" 
      ]