version: '3.4'

services:

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
       - "5675:5672"
    networks: 
      - dapr_aspnetcore

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks: 
      - dapr_aspnetcore

  zipkin:
    image: "openzipkin/zipkin:latest"
    ports:
      - "9412:9411" 
    networks: 
      - dapr_aspnetcore

  dapr-placement:
    image: "daprio/dapr:1.0.0"
    command: ["./placement", "-port", "50005", "-log-level", "debug"]
    networks: 
      - dapr_aspnetcore

  ####################################################################
  # Web Api Service and dapr services
  ####################################################################
  News_WebApi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on: 
      - rabbitmq
      - redis
      - zipkin
      - dapr-placement     
    ports:
      - "11562:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "./log/News.Web.Api:/app/bin/Debug/netcoreapp3.1/Log"
    networks: 
      - dapr_aspnetcore

  News_WebApi-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      # Notice!! --app-id value must lowercase. If you're not use lowercase, 
      # You will get 500 Internal Server Error from response result.
      "-app-id", "news_webapi", 
      "-app-port", "80",
       #"--dapr-http-port", "3500",
       #"--dapr-grpc-port", "50001",
      "-placement-host-address", "dapr-placement:50005",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes: 
      - "./dapr/Components:/components"
      - "./dapr/Config:/configuration"
    depends_on:
      - News_WebApi
    network_mode: "service:News_WebApi"

  Article_WebApi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on: 
      - rabbitmq
      - redis
      - zipkin
      - dapr-placement     
    ports:
      - "11563:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "./log/Article.Web.Api:/app/bin/Debug/netcoreapp3.1/Log"
    networks: 
      - dapr_aspnetcore

  Article_WebApi-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      # Notice!! --app-id value must lowercase. If you're not use lowercase, 
      # You will get 500 Internal Server Error from response result.
      "-app-id", "article_webapi", 
      "-app-port", "80",
      # "--dapr-http-port", "3500",
      # "--dapr-grpc-port", "50001",
      "-placement-host-address", "dapr-placement:50005",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes: 
      - "./dapr/Components:/components"
      - "./dapr/Config:/configuration"
    depends_on:
      - Article_WebApi
    network_mode: "service:Article_WebApi"

  MainWebApi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on: 
      - rabbitmq
      - redis
      - zipkin
      - dapr-placement     
    ports:
      - "11561:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - "./log/MainWebApi:/app/bin/Debug/netcoreapp3.1/Log"
    networks: 
      - dapr_aspnetcore

  MainWebApi-dapr:
    image: "daprio/dapr:latest"
    command: [
      "./daprd", 
      # Notice!! --app-id value must lowercase. If you're not use lowercase, 
      # You will get 500 Internal Server Error from response result.
      "-app-id", "MainWebApi", 
      "-app-port", "80",
      # "--dapr-http-port", "3500",
      # "--dapr-grpc-port", "50001",
      "-placement-host-address", "dapr-placement:50005",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml",
      "--log-level", "debug"
      ]
    volumes: 
      - "./dapr/Components:/components"
      - "./dapr/Config:/configuration"
    depends_on:
      - MainWebApi
    network_mode: "service:MainWebApi"


networks:
  dapr_aspnetcore: 